# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormcustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
