# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_ormcustomer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormcustomer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
