# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ormbankaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormbankaccount',
            name='number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
