# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180713_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormbankaccount',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
