

DEFAULT_PAGINATOR_PAGE = 1
DEFAULT_PAGINATOR_PAGE_SIZE = 5
BANK_ACCOUNT_TYPE_SAVINGS_ACCOUNT = 'SAVINGS_ACCOUNT'
BANK_ACCOUNT_TYPE_CURRENT_ACCOUNT = 'CURRENT_ACCOUNT'
BANK_ACCOUNT_TYPE_SALARY_ACCOUNT = 'SALARY_ACCOUNT'
BANK_ACCOUNT_TYPE_CHOICES = (
    (BANK_ACCOUNT_TYPE_SAVINGS_ACCOUNT, 'Cuenta de ahorros'),
    (BANK_ACCOUNT_TYPE_CURRENT_ACCOUNT, 'Cuenta corriente'),
    (BANK_ACCOUNT_TYPE_SALARY_ACCOUNT, 'Cuenta sueldo')
)